### PR TITLE
Pure maven metadata version selector

### PR DESCRIPTION
**Pull request by simonati**
This PR creates a new ChoiceList based on version data stored in maven-metadata.xml for a single artifact.

image

Possible improvement can be individual artifact selection, so kept the approach of returning whole urls instead of just the version string, but the current version is already helpful in my use-case.

### CODE REVIEW

**Comment by phreakadelle** [comment]
Hey @simonati and thanks again for this PR. I am not convinced yet how you have implemented it. The reason for that is, that this only works for one single repository and not for all of them. Maybe it would be a better idea to have a tick-box that only returns version information. This would work for all repository types.

**Comment by simonati** [comment]
Hi @phreakadelle,

Not so sure about what you meant by “only works for one single repository” I checked with our nexus2 and nexus3 and the implementation relies only on “maven protocol” which in theory makes it agnostic to any artifactory implementation supporting maven. So I guess you meant something different here. Could you please explain in a bit more detail?

Related to the tickbox idea: would it be for each choice list provider or something else? What different behavior would you expect? Sorry I also need some clarification here.

I had to avoid calling rest api in this  one since our latest and greatest  freshly migrated nexus3 is unable to provide the desired information.

**Comment by simonati** [comment]
Hi @phreakadelle,
Just a friendly reminder. I'm still confused a bit about your request for improvements.

**Comment by phreakadelle** [comment]
Hey @simonati and sorry for the delay. I need to compile the plugins by myself and test wha you have done here. Maybe i am confused as well. Will check it next week.

**Comment by phreakadelle** [comment]
I still have it on my radar...

**Comment by phreakadelle** [comment]
Hey @simonati . It took some time but i have checked your PR. I've made some modifications to your feature branch and changed also the interface, so that the "callService" method can directly throw a checked exception. I think it shouldnt be a problem to understand what i have changed. Just let me know if you are good to go and then we merge your PR.

**Comment by phreakadelle** [comment]
@simonati Let let me know if you still need time, otherwise i will merge the PR this week.

**Comment by simonati** [comment]
Hi @phreakadelle Thanks for your changes, they make sense to me! 

+1

**Comment by phreakadelle** [comment]
1.8.0 is available

**Pull request merged**
