### PR TITLE
[JENKINS-68509] Fix JAXBContext class loader context

### PR DESCRIPTION
**Pull request by alecharp**
see [JENKINS-68509](https://issues.jenkins.io/browse/JENKINS-68509).

This is a follow-up of #25, the content of this PR is relatively small and simple if you review #25 first. 

cc @phreakadelle

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by alecharp** [comment]
I'm going to rebase this on top of #25 latest commits, so sorry in advance but I will force push on the branch.

**Comment by alecharp** [comment]
second force push only to sign the commit. Sorry for that. The important commit here is https://github.com/jenkinsci/maven-artifact-choicelistprovider-plugin/pull/26/commits/54ba087eae77be96405cde761151040a3165bec7

**Comment by alecharp** [comment]
In the end, the build is failing because it's trying to run the tests with  Jenkins 1.651.2. This is because it's not using the `Jenkinsfile` I updated in #25 (because I don't have write permissions on the repo), but it's using the `Jenkinsfile` currently on `master` branch.

**Comment by basil** [comment]
@alecharp Do you intend to rebase this PR on top of the main branch? It cannot be merged cleanly otherwise.

**Comment by alecharp** [comment]
sorry I didn't take the time to do that before @basil. @phreakadelle could you review / merge this PR and probably release the plugin with it? Thanks.

**Review by basil — APPROVED** [review]

**Comment by phreakadelle** [comment]
@basil: So we are ready for the release now? Then i will do it today.

**Comment by basil** [comment]
Thank you for the timely responses!

**Pull request merged**
